name: build containers (bootc)
run-name: building containers (bootc)

on:
  workflow_dispatch:

jobs:
  build:
    name: build-containers-bootc
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Fetch shared configuration
        uses: gbraad-actions/shared-config@v1
        with:
          config_repo: https://github.com/gbraad/shared-config.git
          config_file: ${{ github.repository }}/config.ini

      - name: Run podman build - base-bootc
        run: |
          podman build -t ghcr.io/gbraad-trilby/base-bootc:41 \
            --build-arg=BASE_IMAGE=${{ env.BOOTC_IMAGE }} \
            --build-arg=${{ env.BASE_VERSION }} \
            -f containers/Containerfile-base .

      - name: Login to ghcr.io
        run: |
          podman login ghcr.io -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to ghcr.io - base-bootc
        run: |
          podman push ghcr.io/gbraad-trilby/base-bootc:41
